# Generated by Django 4.0.4 on 2022-06-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_productos_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='IdProducto'),
        ),
    ]
