# Generated by Django 4.0.4 on 2022-06-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='idCategorias'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='idProducto'),
        ),
    ]
